### ISSUE TITLE
hello,my computer get blue screen,and back with my data gone

### ISSUE THREAD

**Issue by yelleyee** [koka-lang/madoko#15]
when i open https://www.madoko.net/editor.html in chrome after reboot, the page return me https://www.madoko.net/editor.html#tab=2, but i think my article is in #tab=1 or 0,how can i get it back,or recover from local cache, thx!!!!

**Comment by maelvalais** [comment]
Did you manage to recover your files?

**Comment by yelleyee** [comment]
yes! thx anyway, for developing this good website
