### ISSUE TITLE
Cannot tell the difference between emphasized text and normal in preview pane

### ISSUE THREAD

**Issue by ahhsia** [koka-lang/madoko#20]
Under a stock install of both chrome(60) and firefox (52), I cannot tell the difference between text that is **emphasized** and that which is not. See attached

![madoko](https://user-images.githubusercontent.com/2042495/28942794-e5be0e2e-7859-11e7-8ec9-f1b637e9c627.png)

So configuration problem on my end? 
Any way to change the default rendering in the preview pane?

**Comment by daanx** [comment]
It looks like everything is already emphasized? Perhaps try to refresh or check your markdown if there is no unclosed emphasized block?
