### ISSUE TITLE
Problem with accessing files on Dropbox | Synchronization failed: Bad Request: v1_retired

### ISSUE THREAD

**Issue by CursingRabbit** [koka-lang/madoko#22]
I wanted to continue working on a document after a break. I opened the editor on [https://www.madoko.net/editor.html](https://www.madoko.net/editor.html) but I cannot access the file located on dropbox.
The log messages are:

```
Ready
Connected to Dropbox
Synchronization failed: Bad Request: v1_retired
```

I tried to open another document or creating a new file on Dropbox, but I cannot even navigate through Dropbox to any folder:
<img width="526" alt="2017-09-28 22_06_35-madoko_2 - anatomy" src="https://user-images.githubusercontent.com/15199213/30988298-518f551a-a49a-11e7-8944-479d6c3b5f96.png">

Signing out of Dropbox and signing back in again does not help.

I am still able to navigate to onedrive and access and create new documents there.

It turns out, that Dropbox just shut down version 1 of their API:

> September 28, 2017: API v1 endpoints are turned off.

https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/

So, I removed the Madoko as an app from my dropbox account and tried to link it again by signin out and in again. After login in I get the following error message from Dropbox:

```
Could not login.
Unknown remote service. (Are cookies blocked from https://www.madoko.net?)
```
Cookies are not blocked for madoko in my case.

Is it possible, that Madoko has to be updated to Dropbox new API?

**Comment by daanx** [comment]
Thanks! --  Fixed it by upgrading to the new API.
