### ISSUE TITLE
Clicking on ? link next to available commands menu does not lead to the Madoko reference

### ISSUE THREAD

**Issue by CursingRabbit** [koka-lang/madoko#23]
Clicking in the menu on the question mark '?' link for a specific command does not lead to the Madoko reference. The link point for example for the help on the bibliography to:

http://research.microsoft.com/en-us/um/people/daan/madoko/doc/reference.html#sec-bib

But one gets redirected to:
https://www.microsoft.com/en-us/research/people/daan/?from=http%3A%2F%2Fresearch.microsoft.com%2Fen-us%2Fum%2Fpeople%2Fdaan%2Fmadoko%2Fdoc%2Freference.html#!sec-metadata

The reference is properly linked in the help menu on the top right corner of the editor window. It point to:
http://madoko.org/reference.html

**Comment by daanx** [comment]
Thanks for spotting this -- the links should work now (version 1.1.5 -- you may need to refresh in the browser to update)
