### ISSUE TITLE
[Question] Why does madoko HTML output include .sty files?

### ISSUE THREAD

**Issue by mattpalermo** [koka-lang/madoko#47]
Running `madoko madoko.mdk` produces the following files in the `out` dir:

```
ellipse.sty  longbox.sty  longfbox.sty  madoko2.sty  madoko.css  madoko.html  options.sty
```

I am curious to know why these are output. I tried to read the source code but I'm having trouble reading Koka without learning it.

**Comment by zivbk1** [comment]
These are related to the LaTeX processor that would make the PDF file.

**Comment by mattpalermo** [comment]
I thought that might be why. So it wouldn't cause any harm if these were to be suppressed?

**Comment by zivbk1** [comment]
For HTML output, you should only need ```madoko.css  madoko.html```

**Comment by mattpalermo** [comment]
Thankyou. I've read more of the user manual now and see that madoko can make use of LateX to produce some parts of the HTML output so I guess I shouldn't be too surprised to see LateX related files.
