### ISSUE TITLE
Latex Packages

### ISSUE THREAD

**Issue by ofrades** [koka-lang/madoko#49]
Imagine I want to have a bilingual book with side-by-side text with nice lettrines. In LaTex I would use Paracol and Lettrine Packages and do something like:

```
\usepackage{paracol}
\usepackage{lettrine}
```

And then the text would look like:

```
\begin{paracol}{2}
\lettrine{s}{ome} text
\switchcolumn
\lettrine{s}{ome}  other text
\switchcolumn*
some text
\switchcolumn
some text
\end{paracol}
```

Is this possible to do with madoko? I know that markdown can do tables but it is very basic.

**Comment by RandomFrenchman** [comment]
If I remember well, this should do the trick.

```
Package : paracol
Package : lettrine
```

```
~ Snippet
\begin{paracol}{2}
\lettrine{s}{ome} text
\switchcolumn
\lettrine{s}{ome}  other text
\switchcolumn*
some text
\switchcolumn
some text
\end{paracol}
~
```
